# SAM configuration file
# Archivo de configuración para facilitar el despliegue

version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "invierte-ya-fondos-dev"
s3_prefix = "invierte-ya-fondos"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ProjectName=invierte-ya-fondos"
image_repositories = []
resolve_s3 = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "invierte-ya-fondos-staging"
s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-1234567890"
s3_prefix = "invierte-ya-fondos"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging ProjectName=invierte-ya-fondos"
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "invierte-ya-fondos-prod"
s3_bucket = "aws-sam-cli-managed-prod-samclisourcebucket-1234567890"
s3_prefix = "invierte-ya-fondos"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod ProjectName=invierte-ya-fondos"
image_repositories = []